file = open("codingal.txt","r")
print("File in read mode")
print(file.read())
file.close()
file_write = open("codingal.txt","w")
file_write.write("File in write mode.")
file_write.write("This is a new text")
file_write.close()
file_append = open("codingal.txt","a")
file_append.write("\nFile in append mode.")
file_append.write("New text in append mode.")
file_append.close()